[package]
name = "network_monitor"
version = "0.1.0"
edition = "2021"



[dependencies]
pnet = "0.33"
pcap = "1.0"
sysinfo = "0.29"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }